import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//components
import MainHeader from "../../components/Header";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"w-screen h-screen pt-28"}>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
