import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//components
import MainHeader from "../../components/Static/MainHeader";
import MainFooter from "../../components/Static/MainFooter";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"w-screen h-screen bg-gray-100 "}>
        <MainHeader />
        {children}
        <MainFooter />
      </body>
    </html>
  );
}
